var palabrasSecretas = ["felicidad", "diversion", "amistad", "delicioso", "aventura", "compartir", "bienestar", "asombroso", "imaginacion", "objetivo",];
var palabraSorteada;
var nuevaLetra;
var acierto;
var parrafo = document.getElementById("palabra");
var cant_errores = 0;
var cant_aciertos = 0;
var letrasUsadas = document.getElementById("letrasUsadas");
const imagen = document.getElementById( 'error' );
var avisoFinal = document.getElementById("avisoFinal");
avisoFinal.style.display = "none";
var botonInic = document.getElementById("iniciar");
var botonAgPal = document.getElementById("agPalabra");
var botonAgregar = document.getElementById("agregar");
botonAgregar.style.display = "none";
var dialogoAgPal = document.getElementById("palNueva");
dialogoAgPal.style.display = "none";
var botonDecl = document.getElementById("declinar");
botonDecl.style.display = "none";
botonInic.addEventListener("click", sortearPalabra);
botonDecl.addEventListener("click", declinar);
botonAgPal.addEventListener("click", accederAgPalabra);